package problems;

/*
 * 	Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
public class Problem2 {

	public static void main(String[] args)
	{
		Test(4000000);
	}
	
	private static void Test(int max)
	{
		int firstElement = 1;
		int secondElement = 2;
		int total = 0;
		
		do 
		{
			System.out.println(firstElement);
			
			int result = firstElement % 2;
			
			if (result == 0)
			{
				total += firstElement;
			}
			
			int temp = firstElement + secondElement;
			
			firstElement = secondElement;
			secondElement = temp;	
		}
		while (firstElement <= max);
		
		System.out.println("Total sum od even-value items: " + total);
	}
	
}
